version: "3.9"
services:
  pwiz-watch:
    image: pwiz-watch
    build: .
    platform: linux/amd64         # pwiz image is amd64-only
    volumes:
      - ./data:/data
    environment:
      WATCH_DIR: /data
      OUTPUT_DIR: /data/mzML
      QUIET_SECONDS: "10"
      CHECK_INTERVAL: "5"
      BOOTSTRAP: "1"
      FORMAT: "mzML"              # or "mzXML"
      GZIP: "1"                   # write .mzML.gz
      LOG_LEVEL: "DEBUG"
      WINEDEBUG: "-all"
    restart: unless-stopped